### ISSUE TITLE
How to use this model to infer on own images

### ISSUE THREAD

**Issue by li-bowen-official** [Zhaoyi-Yan/DCANet#1]
Hello, I think you've done great work here. One of the most comprehensive models that is trained on multiple types of datasets for a more one size fits all approach.

I would also like to use your model for my own images to get my own headcount on my own computer, how would I do that? I am able to follow your instructions for making the JSTL_large_dataset, and I had edited the code to see the headcount for each image. But I cannot get it to infer my own images that do not have ground truth.

Could I get some help, please? Please treat me as a newbie and be very clear on even things you find simple. Thank you.

**Comment by Zhaoyi-Yan** [comment]
I have added `test_unknown` folder for your case.
